version: "3.9"

services:
  postgres:
    image: postgres:14.2
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - come-across-postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
    image: come_across_app
    volumes:
      - .:/app
    links:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e development -p 3000 -b '0.0.0.0'"
volumes:
  come-across-postgres:
