default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>

development:
  <<: *default
test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_NAME'] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
